{$IFDEF RELEASE}
  {$A+,B-,D-,E-,F+,G+,I-,L-,N+,Q-,R-,S-,X+,Y-}
{$ENDIF}
{$IFDEF FPC}
  {SMARTLINK ON}
{$ENDIF}
Unit r8FtsPC;

Interface

const
  n = 271;
  ProgramsPC : array[0..n] of string[27] = (
     'Fido',
     'Rover',
     'SEAdog',
     'WinDog',
     'Slick-150',
     'Opus',
     'Dutchie',
     'WPL Library',
     'Tabby',
     'SWMail',
     'Wolf-68k',
     'QMM',
     'FrontDoor',
     'GOmail',
     'FFGate',
     'FileMgr',
     'FIDZERCP',
     'MailMan',
     'OOPS',
     'GS-Point',
     'BGMail',
     'ComMotion/2',
     'OurBBS Fidomailer',
     'FidoPcb',
     'WimpLink',
     'BinkScan',
     'D''Bridge',
     'BinkleyTerm',
     'Yankee',
     'uuGate',
     'Daisy',
     'Polar Bear',
     'The-Box',
     'STARgate/2',
     'TMail',
     'TCOMMail',
     'GIGO',
     'RBBSMail',
     'Apple-Netmail',
     'Chameleon',
     'Majik Board',
     'QM',
     'Point And Click',
     'Aurora Three Bundler',
     'FourDog',
     'MSG-PACK',
     'AMAX',
     'Domain Communication System',
     'LesRobot',
     'Rose',
     'Paragon',
     'BinkleyTerm/oMMM/ST',
     'StarNet',
     'ZzyZx',
     'QEcho',
     'BOOM',
     'PBBS',
     'TrapDoor',
     'Welmat',
     'NetGate',
     'Odie',
     'Quick Gimme',
     'dbLink',
     'TosScan',
     'Beagle',
     'Igor',
     'TIMS',
     'Phoenix',
     'FrontDoor APX',
     'XRS',
     'Juliet Mail System',
     'Jabberwocky',
     'XST',
     'MailStorm',
     'BIX-Mail',
     'IMAIL',
     'FTNGate',
     'RealMail',
     'Lora-CBIS',
     'TDCS',
     'InterMail',
     'RFD',
     'Yuppie!',
     'EMMA',
     'QBoxMail',
     'Number 4',
     'Number 5',
     'GSBBS',
     'Merlin',
     'TPCS',
     'Raid',
     'Outpost',
     'Nizze',
     'Armadillo',
     'rfmail',
     'Msgtoss',
     'InfoTex',
     'GEcho',
     'CDEhost',
     'Pktize',
     'PC-RAIN',
     'Truffle',
     'Foozle',
     'White Pointer',
     'GateWorks',
     'Portal of Power',
     'MacWoof',
     'Mosaic',
     'TPBEcho',
     'HandyMail',
     'EchoSmith',
     'FileHost',
     'SFTS',
     'Benjamin',
     'RiBBS',
     'MP',
     'Ping',
     'Door2Europe',
     'SWIFT',
     'WMAIL',
     'RATS',
     'Harry the Dirty Dog',
     'Maximus-CBCS',
     'SwifEcho',
     'GCChost',
     'RPX-Mail',
     'Tosser',
     'TCL',
     'MsgTrack',
     'FMail',
     'Scantoss',
     'Point Manager',
     'IMBINK',
     'Simplex',
     'UMTP',
     'Indaba',
     'Echomail Engine',
     'DragonMail',
     'Prox',
     'Tick',
     'RA-Echo',
     'TrapToss',
     'Babel',
     'UMS',
     'RWMail',
     'WildMail',
     'AlMAIL',
     'XCS',
     'Fone-Link',
     'Dogfight',
     'Ascan',
     'FastMail',
     'DoorMan',
     'PhaedoZap',
     'SCREAM',
     'MoonMail',
     'Backdoor',
     'MailLink',
     'Mail Manager',
     'Black Star',
     'Bermuda',
     'PT',
     'UltiMail',
     'GMD',
     'FreeMail',
     'Meliora',
     'Foodo',
     'MSBBS',
     'Boston BBS',
     'XenoMail',
     'XenoLink',
     'ObjectMatrix',
     'Milquetoast',
     'PipBase',
     'EzyMail',
     'FastEcho',
     'IOS',
     'Communique',
     'PointMail',
     'Harvey''s Robot',
     '2daPoint',
     'CommLink',
     'fronttoss',
     'SysopPoint',
     'PTMAIL',
     'MHS',
     'DLGMail',
     'GatePrep',
     'Spoint',
     'TurboMail',
     'FXMAIL',
     'NextBBS',
     'EchoToss',
     'SilverBox',
     'MBMail',
     'SkyFreq',
     'ProMailer',
     'Mega Mail',
     'YaBom',
     'TachEcho',
     'XAP',
     'EZMAIL',
     'Arc-Binkley',
     'Roser',
     'UU2',
     'NMS',
     'BBCSCAN',
     'XBBS',
     'LoTek Vzrul',
     'Private Point Project',
     'NoSnail',
     'SmlNet',
     'STIR',
     'RiscBBS',
     'Hercules',
     'AMPRGATE',
     'BinkEMSI',
     'EditMsg',
     'Roof',
     'QwkPkt',
     'MARISCAN',
     'NewsFlash',
     'Paradise',
     'DogMatic-ACB',
     'T-Mail',
     'JetMail',
     'MainDoor',
     'Starnet Products',
     'BMB',
     'BNP',
     'MailMaster',
     'Mail Manager +Plus+',
     'BloufGate',
     'CrossPoint',
     'DeltaEcho',
     'ALLFIX',
     'NetWay',
     'MARSmail',
     'ITRACK',
     'GateUtil',
     'Bert',
     'Techno',
     'AutoMail',
     'April',
     'Amanda',
     'NmFwd',
     'FileScan',
     'FredMail',
     'TP Kom',
     'FidoZerb',
     '!!MessageBase',
     'EMFido',
     'GS-Toss',
     'QWKDoor',
     'No product id allocated',
     '16-bit product id',
     'Reservered',
     'The Brake!',
     'Zeus BBS',
     'XenoPhobe-Mailer',
     'None',
     'Terminate',
     'TeleMail',
     'CMBBS',
     'Shuttle',
     'Quater',
     'Windo',
     'Xenia',
     'GMS',
     'HNET',
     'Shotgun Professional',
     'SLIPgate');

Function ftspcGetProgramName(PC:word):string;

Implementation

Function ftspcGetProgramName(PC:word):string;
begin
  If PC>n then PC:=$FE;
  ftspcGetProgramName:=ProgramsPC[PC];
end;

End.