Unit Lng;

interface

Type
  LngItems  = (
    lngReadConf,
    lngConfLoaded,
    lngInvalidAreafixArc,
    lngIncorrectNumberOfParams,

    lngReadScripts,

    lngInvalidAnnounceArea,
    lngInvalidAnnounceFromName,
    lngInvalidAnnounceToName,
    lngInvalidAnnounceFromAddress,
    lngInvalidAnnounceToAddress,

    lngInvalidEchotype,
    lngCantCreateFile,

    lngDuplicateEntry,
    lngInvalidAreaType,
    lngInvalidGroup,
    lngInvalidFlag,
    lngInvalidNode,
    lngNoBadmail,
    lngNoDupemail,
    lngNotOneBadmail,
    lngNotOneDupemail,

    lngDone,

    lngUnpackingArchives,
    lngPackingOutboundMail,
    lngProcessing,
    lngPackerError,
    lngUnknownPacker,
    lngPackingFor,
    lngLinkIsBusy,
    lngPackingToBusyOutbound,

    lngTossingMessages,
    lngTossingLocal,
    lngDisablingSecurity,
    lngProcessingPackets,
    lngProcessingPacket,
    lngBadPacket,
    lngBadPacketDestination,
    lngBadPacketPassword,
    lngPktMessage,
    lngPktMessageSkipped,
    lngPktMessageTossedToBadmail,
    lngPktMessageTossedToDupeMail,
    lngUnknownArea,
    lngAutocreatedToGroup,
    lngBCLReceived,
    lngClosingBases,
    lngWritingImportList,
    lngExportingBads,
    lngCantOpenBadmail,
    lngCantOpenDupemail,

    lngScanningMessages,
    lngDisablingHighwaters,
    lngExportingMessage,
    lngFailedToOpenBase,

    lngPurgingBases,
    lngNumbOfPurged,

    lngPackingBases,
    lngDescriptingBases,

    lngScanningAreafixNetmail,
    lngBadPassword,
    lngBadPasswordSubj,
    lngUnknownNode,
    lngUnknownNodeSubj,
    lngProcessingRequest,
    lngAreafixReply,
    lngListWillFollow,
    lngSendingListTo,
    lngSendingListSubj,
    lngBCLWillBeSent,
    lngSendingBCLTo,
    lngHelpWillFollow,
    lngSendingHelpTo,
    lngSendingHelpSubj,
    lngLinkedWillFollow,
    lngSendingLinkedTo,
    lngSendingLinkedSubj,
    lngUnLinkedWillFollow,
    lngSendingUnLinkedTo,
    lngSendingUnLinkedSubj,
    lngAvailWillFollow,
    lngSendingAvailTo,
    lngSendingAvailSubj,
    lngCompressWillFollow,
    lngCompressAccepted,
    lngCompressRejected,
    lngChangedCompress,
    lngSendingCompressTo,
    lngSendingCompressSubj,
    lngPwdAccepted,
    lngChangedPwd,
    lngPktPwdAccepted,
    lngChangedPktPwd,
    lngAreaNotAvailable,
    lngAreaAlreadySubscribed,
    lngAreaSubscribeAccepted,
    lngAreaSubscribedTo,
    lngAreaAlreadyUnSubscribed,
    lngAreaIsLocked,
    lngAreaUnSubscribeAccepted,
    lngAreaUnSubscribedFrom,
    lngRequestForwarded,
    lngRequestForwardedLog,
    lngExpiredForward,
    lngExpiredForwardSubj,
    lngAreaAlreadyPassive,
    lngAreaPassiveAccepted,
    lngAreaPassiveTo,
    lngAreaIsNotPassive,
    lngAreaActiveAccepted,
    lngAreaActiveTo,
    lngNothingToProcess,
    lngUnknownAreaOrMetacommand,
    lngUnallowedAll,
    lngCantOpenArealist,
    lngRulesListWillFollow,
    lngRulesWillFollow,
    lngSendingRulesListTo,
    lngSendingRulesListSubj,
    lngSendingRulesSubj,
    lngSendingRulesTo,
    lngIndexingRules,
    lngIndexedRules,

    lngRoutingMessages,
    lngRoutingMessage,

    lngctlCantFindFile,
    lngctlUnknownKeyword,
    lngctlLoopInclude
  );

implementation

end.